<HTML>
-	    <head>
-	        <META http-equiv="content-type" content="text/html; charset=utf-8">
-	    </head>
-	    <body>
-	        <TABLE border=1>
-	            <TR>
-	                <TH>아이디</TH>
-	                <TH>이름</TH>
-	                <TH>전화번호</TH>
-	            </TR>
-	            <TR>
-	                <TD>KHD</TD>
-	                <TD>강호동</TD>
-	                <TD>010-1234-1234</TD>
-	            </TR>
-	            <TR>
-	                <TD>YJS</TD>
-	                <TD>유재석</TD>
-	                <TD>010-1111-1111</TD>
-	            </TR>
-	            <TR>
-	                <TD>PSR</TD>
-	                <TD>박세리</TD>
-	                <TD>010-2222-1234</TD>
-	            </TR>
-	        </TABLE>            
-	    </body>
-	</HTML>
